### ISSUE TITLE
There are a few small issues

### ISSUE THREAD

**Issue by monkeycc** [sotanakamura/winui-python#4]
This framework is very cool
Thank you for being open-source

There are a few small questions that need to be consulted

1. The startup seems a bit slow
2. After the demo program starts, the mouse remains in the read state
3. If packaging and deploying, do other users need to install the Windows App SDK
4. Lack of sample documents, hoping to add more documents and examples
5. I will recommend more people to use this framework

**Comment by sotanakamura** [comment]
First of all, the objective of this sample code is introducing  [py-win32more](https://github.com/ynkdir/py-win32more) for WinUI 3. Please contribute to the original project.

> The startup seems a bit slow

Yes, it is because the file size of the library is very huge.

> After the demo program starts, the mouse remains in the read state

I don't know about it.

> If packaging and deploying, do other users need to install the Windows App SDK

Yes. If you don't like it, you can use a MSIX package. The MSIX install Windows App Runtime automatically and resolves the dependency. 

> Lack of sample documents, hoping to add more documents and examples

This is just a sample code. Please contribute to the original project, [py-win32more](https://github.com/ynkdir/py-win32more). [The original repository contains some examples.](https://github.com/ynkdir/py-win32more/tree/main/example)

> I will recommend more people to use this framework

Me too!
